name: Deploy to Azure Dev VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP_VM_DEV }}
          username: adminuser
          key: ${{ secrets.SSH_PRIVATE_KEY_VM_DEV }}
          script: |
            sudo git config --global --add safe.directory /var/www/html
            cd /var/www/html
            
            # 1. Si le dossier .git n'est pas là, on clone d'abord
            if [ ! -d ".git" ]; then
              sudo git clone https://github.com/Scorpierre/my-azure-crm.git .
              sudo chown -R adminuser:adminuser /var/www/html
            fi

            # 2. On récupère les nouveautés
            sudo git fetch --all
            sudo git reset --hard origin/main
            
            # 3. On build et on lance
            sudo npm install
            sudo npm run build
            
            # On vérifie si PM2 tourne déjà, sinon on lance le premier démarrage
            sudo pm2 restart all || sudo pm2 start dist/main.js --name "nest-app"